build:
  runs-on: ubuntu-latest
  env:
    MDBOOK_VERSION: 0.4.52

  steps:
    - uses: actions/checkout@v4

    - name: Install mdBook
      run: |
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
        source "$HOME/.cargo/env"
        cargo install --version ${MDBOOK_VERSION} mdbook

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Build ForgeLang Book
      run: |
        cd Docs/docs
        mdbook build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./Docs/docs/book